[package]
name = "todos-with-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
diesel = { version = "2.1.5", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
