services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_axum
    ports:
      - "3000:3000"
    restart: always
  db:
    container_name: todo_axum_db
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - todo_axum_postgres_data:/var/lib/postgresql/data
  test:
    container_name: todo_axum_test

volumes:
  todo_axum_postgres_data: {}
