name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: my_password
          POSTGRES_USER: my_user
          POSTGRES_DB: my_database

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3

    - name: Use nightly release
      run: rustup default nightly
    
    - name: Run tests
      env:
        DATABASE_URL: postgres://my_user:my_password@localhost/my_database
      run: cargo test
